---
namespace: trippsc2
name: vmware
version: 1.3.1
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains roles and modules for managing VMware infrastructure.

license_file: 'LICENSE'

tags:
  - cloud
  - infrastructure

dependencies:
  community.vmware: '>=1.0.0'

repository: https://github.com/trippsc2/ansible-collection-vmware.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
