---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: deploy_vm
  description: This role deploys and customizes a new VMware VM from a template.
  license: MIT

  min_ansible_version: '2.15'

  platforms: []

collections:
  - community.vmware

dependencies: []
